USE [master]
GO
CREATE LOGIN [zSvc_AG_Status] WITH PASSWORD=N'rations-EVHv2wf6neQuNzRx=83S', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

USE [master]
CREATE SERVER ROLE [Role_AG_Status];
GO

use [master]
GRANT SELECT ALL USER SECURABLES TO [Role_AG_Status];
GRANT VIEW ANY DATABASE TO [Role_AG_Status];
GRANT VIEW ANY DEFINITION TO [Role_AG_Status];
GRANT VIEW SERVER STATE TO [Role_AG_Status];
GO

ALTER SERVER  Role [Role_AG_Status] ADD MEMBER [zSvc_AG_Status];
