
/****** Object:  Index [PK_xxxxx_ID]    Script Date: 6/7/2013 11:28:20 AM ******/
 ALTER TABLE dbo.td_CdCl ADD CONSTRAINT [PK_td_CdCl] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

CREATE NONCLUSTERED INDEX [IX_td_CdCl_ETL_UpdateDateTime] ON [dbo].[td_CdCl]
(
	[ETL_UpdateDateTime] ASC,
	[ID] ASC
)
	WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

/****** Object:  Index [IX_xxxxx_SubID]    Script Date: 6/7/2013 11:31:30 AM ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_td_CdCl_ID] ON [dbo].[td_CdCl]
(
	--[SubID] ASC,
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
