USE [master]
GO

ALTER DATABASE [ARSystem] ADD FILEGROUP [CDC];
GO

ALTER DATABASE [ARSystem] ADD FILE ( NAME = N'AR_CDC', FILENAME = N'M:\Vi303_Data\CDC\AR_CDC.ndf' , SIZE = 1048576KB , FILEGROWTH = 1048576KB ) TO FILEGROUP [CDC];
GO

USE [ARSystem]
GO

IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'CDC') 
	ALTER DATABASE [ARSystem] MODIFY FILEGROUP [CDC] DEFAULT;
GO

EXEC sp_cdc_enable_db;
GO

ALTER DATABASE [ARSystem] MODIFY FILEGROUP [PRIMARY] DEFAULT;
GO